name: CI/CD Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect & Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/downloadbotdeploy/downloadbot
            git pull origin main
            docker build -t telegram-bot .
            docker stop tg-bot || true
            docker rm tg-bot || true
            docker run --env-file .env --restart unless-stopped -d --name tg-bot telegram-bot
