name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - main
      - stage

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/downloadbotdeploy/downloadbot

            echo "Обновляем репозиторий на ветке ${{ github.ref_name }}"
            git fetch origin
            git checkout ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}

            if [ "${{ github.ref_name }}" = "stage" ]; then
              echo "🚧 Test(staging) deploy"
              docker build -t telegram-bot-stage .
              docker stop tg-bot-stage || true
              docker rm tg-bot-stage || true
              docker run --env-file stage.env --restart unless-stopped -d --name tg-bot-stage telegram-bot-stage

            elif [ "${{ github.ref_name }}" = "main" ]; then
              echo "🚀 Prod deploy"
              docker stop tg-bot-stage || true
              docker rm tg-bot-stage || true
              docker build -t telegram-bot .
              docker stop tg-bot || true
              docker rm tg-bot || true
              docker run --env-file .env -v /home/downloadbotdeploy/data:/app/data --restart unless-stopped -d --name tg-bot telegram-bot
            fi

      - name: Send Telegram Notification (success)
        if: success()
        run: |
          MESSAGE="✅ Деплой для ветки \`${{ github.ref_name }}\` завершён."
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.NOTIFY_TOKEN }}/sendMessage" -d chat_id=${{ secrets.NOTIFY_CHAT_ID }} -d parse_mode=Markdown --data-urlencode "text=$MESSAGE"

      - name: Send Telegram Notification (failure)
        if: failure()
        run: |
          MESSAGE="❌ Ошибка при деплое в ветку \`${{ github.ref_name }}\`"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.NOTIFY_TOKEN }}/sendMessage" -d chat_id=${{ secrets.NOTIFY_CHAT_ID }} -d parse_mode=Markdown --data-urlencode "text=$MESSAGE"
